
export const SET_CURRENT_CATEGORY='SET_CURRENT_CATEGORY';

export const SET_SLIDERS='SET_SLIDERS';

export const SET_LOADING_LESSONS = 'SET_LOADING_LESSONS';
export const SET_LESSONS='SET_LESSONS';
export const FETCH_LESSONS='FETCH_LESSONS';
